Repository Azure/react-azure-maps, pull requests merged in 2020-03, with the labels that each got.

#35 feat: Shape as state in feature component
  src/components/AzureMapFeature/AzureMapFeature.tsx
  src/components/AzureMapFeature/useCreateAzureMapFeature.ts
  src/components/AzureMapFeature/useFeature.ts
  src/types.ts
Labels: notMerge

#40 feat: custom image sprite
  src/components/AzureMap/useCreateSprites.tsx
  src/types.ts
Labels: enhancement

#42 feat: datasource touch-ups, adjust to spatial-io
  package.json
  src/contexts/AzureMapDataSourceContext.tsx
  src/types.ts
  yarn.lock
Labels: dependencies, enhancement

#43 feat: effect on layer options
  src/hooks/useAzureMapLayer.ts
Labels: enhancement

#45 test: layer tests
  __mocks__/azure-maps-control.js
  src/contexts/AzureMapDataSourceContext.tsx
  src/hooks/useAzureMapLayer.test.tsx
  src/hooks/useAzureMapLayer.tsx
  src/types.ts
Labels: notMerge
